#pragma once
#include "includes.h"
#include "PAC_err.h"
#include "lua_manager.h"
#include "mock_params_manager.h"
#include "mock_project_manager.h"
#include "mock_tcp_communicator.h"
#include "mock_tech_object_manager.h"
#include "operation_mngr.h"
