if(EXISTS "/home/runner/work/ptusa_main/ptusa_main/_codeql_build_dir/main_test[1]_tests.cmake")
  include("/home/runner/work/ptusa_main/ptusa_main/_codeql_build_dir/main_test[1]_tests.cmake")
else()
  add_test(main_test_NOT_BUILT main_test_NOT_BUILT)
endif()
