# Normalize tolua++ generated files and rewrite the destination only when
# the real content differs apart from the autogenerated header block (first 4
# lines).

set(TOOLUA_COPY_IF_DIFFERENT_ROOT "${CMAKE_CURRENT_LIST_DIR}")

function(normalize_from_fifth_line FILEPATH OUTPUT_VAR)
    file(READ "${FILEPATH}" _content)
    # Normalize line endings to make comparisons stable across platforms.
    string(REPLACE "\r\n" "\n" _content "${_content}")
    string(REPLACE "\r" "\n" _content "${_content}")

    # Drop the first 4 lines (tolua++ autogenerated header block).
    string(REGEX REPLACE "^([^\n]*\n){0,4}" "" _normalized "${_content}")
    set(${OUTPUT_VAR} "${_normalized}" PARENT_SCOPE)
endfunction()

function(ToluaCopyIfDifferent INPUT OUTPUT)
    if("${INPUT}" STREQUAL "" OR NOT EXISTS "${INPUT}")
        message(FATAL_ERROR
		    "ToluaCopyIfDifferent INPUT file does not exist: '${INPUT}'")
    endif()
    if("${OUTPUT}" STREQUAL "")
         message(FATAL_ERROR
			"ToluaCopyIfDifferent requires a non-empty OUTPUT path")
    endif()

    normalize_from_fifth_line("${INPUT}" INPUT_CONTENT_NORMALIZED)

    if(EXISTS "${OUTPUT}")
        normalize_from_fifth_line("${OUTPUT}" OUTPUT_CONTENT_NORMALIZED)
    else()
        set(OUTPUT_CONTENT_NORMALIZED "")
    endif()

    if(NOT EXISTS "${OUTPUT}" OR NOT "${INPUT_CONTENT_NORMALIZED}" STREQUAL "${OUTPUT_CONTENT_NORMALIZED}")
        if(EXISTS "${OUTPUT}")
            file(REMOVE "${OUTPUT}")
        endif()
        file(RENAME "${INPUT}" "${OUTPUT}")
     else()
        file(REMOVE "${INPUT}")
    endif()
endfunction()

function(regenerate_tolua_file OUTPUT_FILE TOLUA_NAME HEADER_FILE)
    get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
    get_filename_component(OUTPUT_NAME "${OUTPUT_FILE}" NAME)
    get_filename_component(PROJECT_ROOT "${TOOLUA_COPY_IF_DIFFERENT_ROOT}" DIRECTORY)
    file(RELATIVE_PATH OUTPUT_REL_DIR "${PROJECT_ROOT}" "${OUTPUT_DIR}")
    set(TMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_REL_DIR}")
    set(TMP_FILE "${TMP_DIR}/${OUTPUT_NAME}.tmp")

    add_custom_command(
        OUTPUT "${OUTPUT_FILE}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${TMP_DIR}"
        COMMAND toluapp -n ${TOLUA_NAME} -o "${TMP_FILE}" "${HEADER_FILE}"
        COMMAND ${CMAKE_COMMAND}
            -DINPUT="${TMP_FILE}"
            -DOUTPUT="${OUTPUT_FILE}"
            -P "${TOOLUA_COPY_IF_DIFFERENT_ROOT}/ToluaCopyIfDifferent.cmake"
        DEPENDS "${HEADER_FILE}"
        WORKING_DIRECTORY "${PROJECT_ROOT}"
    )
endfunction()

if(DEFINED INPUT AND DEFINED OUTPUT)
    ToluaCopyIfDifferent("${INPUT}" "${OUTPUT}")
endif()
