# Normalize tolua++ generated files and rewrite the destination only when
# the real content differs apart from the autogenerated header line.
set(TOOLUA_COPY_IF_DIFFERENT_ROOT "${CMAKE_CURRENT_LIST_DIR}")

function(normalize_from_fifth_line FILEPATH OUTPUT_VAR)
    file(STRINGS "${FILEPATH}" _lines)
    list(LENGTH _lines _len)
    if(_len GREATER 4)
        list(SUBLIST _lines 4 -1 _lines_after)
    else()
        set(_lines_after "")
    endif()
    list(JOIN _lines_after "\n" _normalized)
    set(${OUTPUT_VAR} "${_normalized}" PARENT_SCOPE)
endfunction()

function(ToluaCopyIfDifferent INPUT OUTPUT)
    if(NOT DEFINED INPUT)
        message(FATAL_ERROR "ToluaCopyIfDifferent requires INPUT variable")
    endif()
    if(NOT DEFINED OUTPUT)
        message(FATAL_ERROR "ToluaCopyIfDifferent requires OUTPUT variable")
    endif()

    normalize_from_fifth_line("${INPUT}" INPUT_CONTENT_NORMALIZED)

    if(EXISTS "${OUTPUT}")
        normalize_from_fifth_line("${OUTPUT}" OUTPUT_CONTENT_NORMALIZED)
    else()
        set(OUTPUT_CONTENT_NORMALIZED "")
    endif()

    if(NOT EXISTS "${OUTPUT}" OR NOT "${INPUT_CONTENT_NORMALIZED}" STREQUAL "${OUTPUT_CONTENT_NORMALIZED}")
        if(EXISTS "${OUTPUT}")
            file(REMOVE "${OUTPUT}")
        endif()
        file(RENAME "${INPUT}" "${OUTPUT}")
    endif()
endfunction()

function(regenerate_tolua_file OUTPUT_FILE TOLUA_NAME HEADER_FILE)
    get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
    get_filename_component(OUTPUT_NAME "${OUTPUT_FILE}" NAME)
    get_filename_component(PROJECT_ROOT "${TOOLUA_COPY_IF_DIFFERENT_ROOT}" DIRECTORY)
    file(RELATIVE_PATH OUTPUT_REL_DIR "${PROJECT_ROOT}" "${OUTPUT_DIR}")
    set(TMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_REL_DIR}")
    set(TMP_FILE "${TMP_DIR}/${OUTPUT_NAME}.tmp")

    add_custom_command(
        OUTPUT "${OUTPUT_FILE}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${TMP_DIR}"
        COMMAND toluapp -n ${TOLUA_NAME} -o "${TMP_FILE}" "${HEADER_FILE}"
        COMMAND ${CMAKE_COMMAND}
            -DINPUT="${TMP_FILE}"
            -DOUTPUT="${OUTPUT_FILE}"
            -P "${TOOLUA_COPY_IF_DIFFERENT_ROOT}/ToluaCopyIfDifferent.cmake"
        DEPENDS "${HEADER_FILE}"
        WORKING_DIRECTORY "${PROJECT_ROOT}"
    )
endfunction()

if(DEFINED INPUT AND DEFINED OUTPUT)
    ToluaCopyIfDifferent("${INPUT}" "${OUTPUT}")
endif()
